### ISSUE TITLE
Synchronization Query always performs an initial synchronization

### ISSUE THREAD

**Issue by ArondeParon** [contentful/contentful.php#10]
The `getQueryData` method in the Synchronization Query object looks like this:

    public function getQueryData()
    {
        $data = [
            'initial' => true,
            'type' => $this->type !== 'all' ? $this->type : null,
            'content_type' => $this->contentType
        ];

        return $data;
    }

This method is called in the `Manager` as following:

    public function startSync(Query $query = null)
    {
        $query = $query !== null ? $query : new Query;
        $response = $this->client->syncRequest($query->getQueryData());

        return $this->buildResult($response);
    }

As you can probably see, this code can not be extended in it's current form. There *is* a way to inject a custom Query object, but there is no way to override the `initial` state.

The problem with this is that it is not possible to performance delta synchronization at all; every sync will return the entire resultset as if it were new.

**Comment by realityking** [comment]
Hi Aron,

have you seen our tutorial on [Using the Sync API with PHP](https://www.contentful.com/developers/docs/php/tutorials/using-the-sync-api-with-php/)? If so, we might need to explain better how the sync API works.

The important part is that you use `startSync()` only for the initial sync. If you want to get the changes since the last synchronisation, you must use `continueSync()`. The reason `'initial' => true` is hardcoded is, that you can only set the type and content type to sync on the initial sync.

Does that clear things up?

**Comment by ArondeParon** [comment]
Hi @realityking, you beat me to it. Just discovered the way this works myself. 

Thanks for clearing this up!

**Comment by realityking** [comment]
Glad it work out. Could you share how we could have made this easier to figure out? It's certainly not the most obvious part of our API.

**Comment by ArondeParon** [comment]
Hi @realityking, the docs are pretty clear, actually. I just didn't see that particular page because it's not listed in the sidebar.

**Comment by realityking** [comment]
Thanks for the feedback. :)
