### ISSUE TITLE
Caching the API Calls

### ISSUE THREAD

**Issue by adiwibisono** [contentful/contentful.php#123]
Hi, 

Just wondering if object caching is happening at all with the PHP SDK? If yes, at which version it is available? I've read the version logs but I just wanted to make sure here.

My api calls are going to the sky (not just roof). I suspect it is because bots are hitting non-existent slugs and goes to 404 with query requests (for menu navigations).  

I checked the code and there is a term of "WarmingUp the Cache" and supposed to be used with the cli command. Is there an example of this object/space caching with php?

Thank you for the answer.

Adi

**Comment by realityking** [comment]
Hi @adiwibisono,

The SDK supports caching the space and content types but nothing else. The warm ups download the space metadata and all content types as the cache is not incrementally build. It turned out that the script to warm up the cache was actually broken (unless using the Symfony Bundle) but those issues were fixed with #125 and #127. They'll be part of the next release.

Afterwards we'll try to get some docs up ASAP.

**Comment by realityking** [comment]
We just released [2.0.0](https://github.com/contentful/contentful.php/releases/tag/2.0.0) that include #125 and #127. We'll have the docs up soon.

**Comment by realityking** [comment]
Hi @adiwibisono,

The tutorial is now available here: https://www.contentful.com/developers/docs/php/tutorials/caching-in-the-php-cda-sdk/

I hope that helps to get it working :)

Cheers,
Rouven
