### ISSUE TITLE
How to query for empty value on URL field

### ISSUE THREAD

**Issue by johnny-cartelle** [contentful/contentful.php#218]
Hello,

I have a Contentful field of type 'short text' that's a URL field and I'm trying to get results where my field "externalUrl' is empty. I've tried many different things but can't seem to exclude items where this field is filled out.  Should this work to find items where my 'externalUrl' field is empty?

$query->where('fields.externalUrl', '');
I've also tried
$query->where('fields.externalUrl[exists]', false);

This is my full query...
$query = new \Contentful\Delivery\Query;
$query->select(['fields.slug']);
$query->setContentType('entries');
$query->where('limit', 1);
$query->where('fields.publishedDate[lt]', $date);
$query->where('fields.externalUrl', '');
$query->orderBy('-fields.publishedDate');
$query->setInclude(1);

The query still returns items where the externalUrl is filled out.

**Comment by dborsatto** [comment]
Hey there,

### Some background:

Our APIs handle fields that are not set and fields that are set to an empty string in a different way. If you're managing content using our Web App only (which is the most common situation), then when you don't populate a field, it will be excluded from the payload, and you can use the `exists` operator to filter that. If you manually use the Management API, and set the field to an empty string, unfortunately currently we don't allow filtering on that. The solution would be so set the value to `null`, so it can become searchable using `exists`.

### Back to your problem:

The issue in your case is tricky to find, but I suspect it boils down to `$query->where('fields.externalUrl[exists]', false);`. Internally the SDK uses `http_build_query` to create the query string, and that function converts the boolean `false` to `0`, for whatever reason. This means that your query will actually become `fields.externalUrl[exists]=0`, which doesn't work. To solve this, simply turn the boolean `false` into a string (`'false'`) and that should do the trick.

### One final note about building the query:

Even though your query eventually turns out to be correct, it's not the best (intended) way of setting the values: `Query::where()` takes a third parameter which is used for specifying the filtering type (like `[exists]`), `Query::orderBy()` takes a boolean second parameter for specifying a descending order, and there's a proper `Query::setLimit()` function instead of using `Query::where()`. The end result is the same, but I suggest for clarity you turn your example query into this:

``` php
$query = new \Contentful\Delivery\Query();
$query->select(['fields.slug'])
    ->setInclude(1)
    ->setLimit(1)
    ->setContentType($contentTypeName)
    ->where('fields.publishedDate', $date, 'lt')
    ->where('fields.externalUrl', 'false', 'exists')
    ->orderBy('fields.publishedDate', true)
;
```

In your example you're using `$query->setContentType('entries')`. I'm not sure whether that's a typo or you actually have a content type named `entries`, but just to be sure, you're supposed to use the content type ID (like `person`, `blogPost`, or whatever you have in your content model) and _not_ `entries` 🙂 

I hope this answers your question. If you need extra help, feel free to continue the discussion, otherwise I'll close this issue in a few days 👍

**Comment by johnny-cartelle** [comment]
Awesome - problem solved. And thanks for the tips! I will implement those as well.
