### ISSUE TITLE
503 between bytes timeout response - Sync API

### ISSUE THREAD

**Issue by mrbenosborne** [contentful/contentful.php#292]
Hi guys,

I am using the Sync API and followed the guide at https://www.contentful.com/developers/docs/php/tutorials/using-the-sync-api-with-php/.

I am using PHP 7.4.4 and contentful/laravel version 6.0.

When I run a full sync or continue sync I sometimes get a 503 error intermittently, see the error below:

![image](https://user-images.githubusercontent.com/7268075/83232964-ea30a400-a185-11ea-9a71-951c7c471407.png)

The summary field stores a fair amount of text data but not massive amounts.

**Comment by pgrigoruta** [comment]
@mrbenosborne , I just tried a sync over a large test space, around 40k records and it worked well. A few things to consider so to move forward:

- can you try again? Wondering if this was a temp thing caused by load issue
- what happens if you try/catch the error and retry? Would the next request work? Or it fails constantly on a specific step?

**Comment by mrbenosborne** [comment]
> @mrbenosborne , I just tried a sync over a large test space, around 40k records and it worked well. A few things to consider to move forward:
> 
> 
> 
> - can you try again? Wondering if this was a temp thing caused by load issue
> 
> - what happens if you try/catch the error and retry? Would the next request work? Or it fails constantly on a specific step?

Yes sure, it seems good now, perhaps it was just a blib, can we implement a retry for that data set if a 503 is returned?

**Comment by pgrigoruta** [comment]
Yes, a retry should be good.
