### ISSUE TITLE
Empty Paragraph Node

### ISSUE THREAD

**Issue by ray-itech** [contentful/contentful.php#302]
Hello,

I have noticed that, Contentful PHP SDK returns an empty `Text` Node, even though I try to remove the new line at the end of a `Rich Text` entry, it always adds a new line by default:

<img width="312" alt="Screenshot 2021-06-14 at 17 52 17" src="https://user-images.githubusercontent.com/63705600/121929649-518da780-cd39-11eb-8139-db9e801b3042.png">

I am using the `Composer` app.

<img width="809" alt="Screenshot 2021-06-14 at 17 50 51" src="https://user-images.githubusercontent.com/63705600/121929391-10959300-cd39-11eb-872b-1d69bebd9646.png">

**Comment by Sebb767** [comment]
Hi @ray-itech ,

sorry for getting back to you so late! It seems like the issue here is in the editor. If the cursor is on the next line, it is internally seen as new paragraph. If you want to avoid this, remove the new line. This, for example, will lead to an empty node:

![i302-1](https://user-images.githubusercontent.com/4084001/127787053-8b3d6377-913d-4876-880f-1a6dbb0982b7.png)

This, on the other hand, won't:

![i302-2](https://user-images.githubusercontent.com/4084001/127787057-1ccffce8-0baf-4fee-a62f-5d133d80d8b7.png)

Please let me know whether this solves your issue.

**Comment by Sebb767** [comment]
@ray-itech Do you have any further questions or did this solve your issue? :)
