### ISSUE TITLE
Contentful Delivery $setLocale * not working as expected

### ISSUE THREAD

**Issue by sebalaini-itm** [contentful/contentful.php#312]
I'm trying to fetch a localized page that has the same slug in a different locale and my logic works for almost every page but seems to work only if the slug I'm requesting it's on the default Locale, and that will break some other pages.

I'm following this documentation https://contentful.github.io/contentful.php/api/master/Contentful/Delivery/Query.html 
and this is part of my code:
```
        const PAGE_CONTENT_TYPE = 'page';
        const ENTRY_LIMIT       = 1;
        const INCLUDES          = 8;
        ....

        $slug = $this->slug === '/' ? $this->slug : trim($this->slug, '/');
        $this->query->setLimit(self::ENTRY_LIMIT);
        $this->query->setContentType(self::PAGE_CONTENT_TYPE);
        $this->query->setInclude(self::INCLUDES);
        // this works only if slug it's on default
        $this->query->setLocale($this->locale === 'default' ? 'default' : '*');
        $this->query->where('fields.slug', $slug);
        $entries = $this->client->getEntries($this->query);
        dd($entries);
```

`$this->locale` it's sometimes set by the 1st part of the slug and sometimes based on Visitor Location if match some criteria.

E.g:
- slug = `/home/`
- `$this->locale` = 'en-CA'

Will return the page with the field slug default = `/home/` and the en-CA = `ca/home/` or `/home/` doesn't matter I can see all of them within the returned entry so it's OK

- slug = `/us/home/` but this one would be set on the `en-US` locale and the default slug can be `/home/`
- `$this->locale` = 'en-CA'

Will return empty `$entries` it's that the expected behavior?

**Comment by Sebb767** [comment]
Hey,

I'm currently looking into this, this might be an API bug. Just so I get this right, you have the following behavior:

- Query with slug = `/home` and locale = `en-US`-> returns the correct entry
- Query with slug = `us/home` and locale = `en-US`-> returns the correct entry
- Query with slug = `ca/home` and locale = `en-CA`-> returns the correct entry
- Query with slug = `us/home` and locale = `en-CA`-> returns nothing, should return same entry

Am I getting this right?

**Comment by Sebb767** [comment]
After some further clarification, the problem seems to be the following: Given a field with a localized value, a query to the field will not search values in different locales. If you don't give a locale or `*`, the API will use the default locale and not search other locales, either. This seems to be a limitation of the API at the moment.

You can do any the following to work around this limitation:

1. Use fulltext search. In this case, instead of `$this->query->where('query', $slug)`, you would  use `$this->query->where('fields.slug', $slug);` . This will search all locales and find results as expected, but will do a full word search on all fields - so it might return more or different results than anticipated (for example, if a text contains this link, it will be found, too). Therefore, it's necessary to filter the results again on the client side in order to extract the correct locale and verify whether it's an actual match.
2. If it's possible to extract the locale from the slug (like in the ca/home example), directly query the field in the correct locale.
3. Another option is to cache a map of `localized slug` to `slug` and use this lookup to query the correct entry with locale *  to get all fields.
4. Lastly, if everything else does not fit, you will need to query in all locales. I'd advice against this, since you will use the API a lot and slow down your page.

**Comment by annikaC** [comment]
Thanks for looking into this @Sebb767 - is the fix for supplying '*' to the query in the API roadmap at all and is there a  booked timeline to fix that you could share with us? 

The workarounds for this are not ideal - like you said, 1. would fetch everything where the slug is mentioned, and 2. doesn't work for dynamic localised content on the same slug, so 3 is looking like the only option at the moment.

**Comment by Sebb767** [comment]
Hi @annikaC ,

> Thanks for looking into this @Sebb767 - is the fix for supplying '*' to the query in the API roadmap at all and is there a booked timeline to fix that you could share with us?

Unfortunately, there is no timeline yet and I don't know whether they plan on changing it - I'm currently in contact with the API team, I will update you once I know more.

> The workarounds for this are not ideal - like you said, 1. would fetch everything where the slug is mentioned, and 2. doesn't work for dynamic localised content on the same slug, so 3 is looking like the only option at the moment.

If you want, I can provide you example code for option 1 - it's probably a lot easier than maintaining a cache.

**Comment by annikaC** [comment]
That would be fantastic, @Sebb767 - thank you!
