### ISSUE TITLE
[Question] Possible to avoid querying Space & ContentType when querying Entries?

### ISSUE THREAD

**Issue by sgb-io** [contentful/contentful.php#34]
When fetching entries, sometimes I want just the entry without resolving any of it's Links.

In particular, the sdk, by default, will query Contentful to resolve the `space` and `contentType` properties in the `SystemProperties` for a single entry when doing a simple `getEntries` call (via `ResourceBuilder:: buildSystemProperties`).

Note that setting `includes` to `0` does not affect this behaviour.

We don't need that data at this point and would like control over when we get that data.

It means that, if I'm not mistaken, 3 requests are sent to `Contentful` to resolve a single entry with `0` `includes`. For us, this is slow and inefficient.

For context, in our use case, we are instantiating many separate Content Delivery `Client`s as part of a background job (via a queue system). Each `Client` is getting some standard entries (via `getEntries`). Because we are making many of these `Client`s, the SDK is forcing many superfluous requests. The `InstanceCache` is not shared between clients so does not help.

Is it possible to avoid this default behaviour, and just keep the `space` and `contentType` as `Link`s?

**Comment by realityking** [comment]
Unfortunately it's not that easy as the `DynamicEntry` needs access to both the space (for the locales) and the content type (for the fields of types) to work correctly.

There are two things planned that will help you eventually:
- Cacheing for space and content types
- A way to request the raw version of entries (meaning just an array of data instead of objects)

Unfortunately neither is going to happen soon.

The best workaround you could do today is the following:
- Fetch the space and all content types
- Persist them to the file system
- When you create the client use [`DeliveryClient::reviveJson`](https://github.com/contentful/contentful.php/blob/11a29b8263fc2f9b65e734418d2b94a9a7779c49/src/Delivery/Client.php#L219-L235) to populate the InstanceCache with the data.

Just make sure you clear the cache when you change your content model ;)

Does that help you?

**Comment by sgb-io** [comment]
Thanks for the speedy response and advice.
